name: VALARHASH

on:
  push:
    branches: [ main ]

jobs:
  beta-deploy:
    runs-on: ubuntu-latest
    steps:0.
     
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        uses: Borales/actions-yarn@v3
        with:
          cmd: install --frozen-lockfile

      - name: Build for production
        uses: Borales/actions-yarn@v3
       
      
      - run: yarn
      - run: yarn build

      - name: Deploy Gh-Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: https://www.valarhashjp.com
